### ISSUE TITLE
Params not passing to EGW

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/data-api#1111]
For shared-key based vectorize auth: 
Data API will make grpc call to EGW, and EGW makes http call to Sync-Service.
Somehow, params is not passing from Data API to EGW, which will cause Sync-Service return null pointer exception.

Stack Trace:
```

ERROR [vert.x-eventloop-thread-0] 2024-05-22 09:15:42,775 EmbeddingServiceImpl.java:181 - {"tenantId":"123","embeddingProvider":"openai","model":"text-embedding-3-small","error":{"errorCode":"SERVER_UNHANDLED_ERROR","errorMsg":"java.lang.NullPointerException: Param was null"}}: io.quarkus.cache.CacheException: java.lang.NullPointerException: Param was null
        at io.quarkus.cache.runtime.CacheResultInterceptor$2.apply(CacheResultInterceptor.java:71)
        at io.quarkus.cache.runtime.CacheResultInterceptor$2.apply(CacheResultInterceptor.java:62)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl$3$1.apply(CaffeineCacheImpl.java:114)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl$3$1.apply(CaffeineCacheImpl.java:110)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncAsMapView.lambda$computeIfAbsent$0(LocalAsyncCache.java:366)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncAsMapView.computeIfAbsent(LocalAsyncCache.java:365)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache$AsyncAsMapView.computeIfAbsent(LocalAsyncCache.java:293)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl$3.get(CaffeineCacheImpl.java:109)
        at io.quarkus.cache.runtime.caffeine.CaffeineCacheImpl$3.get(CaffeineCacheImpl.java:103)
        at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniEmitOn.subscribe(UniEmitOn.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)
        at io.quarkus.grpc.stubs.ServerCalls.oneToOne(ServerCalls.java:38)
        at io.stargate.embedding.gateway.MutinyEmbeddingServiceGrpc$MethodHandlers.invoke(MutinyEmbeddingServiceGrpc.java:118)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.quarkus.opentelemetry.runtime.tracing.intrumentation.grpc.GrpcTracingServerInterceptor$TracingServerCallListener.onHalfClose(GrpcTracingServerInterceptor.java:143)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.quarkus.grpc.ExceptionHandler.onHalfClose(ExceptionHandler.java:36)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.quarkus.grpc.runtime.supports.context.GrpcRequestContextGrpcInterceptor$1.onHalfClose(GrpcRequestContextGrpcInterceptor.java:84)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.quarkus.grpc.ExceptionHandler.onHalfClose(ExceptionHandler.java:36)
        at io.quarkus.grpc.runtime.supports.context.GrpcDuplicatedContextGrpcInterceptor$ListenedOnDuplicatedContext.lambda$invoke$0(GrpcDuplicatedContextGrpcInterceptor.java:141)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
        at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Param was null
        at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.resolveTemplate(WebTargetImpl.java:112)
        at org.jboss.resteasy.reactive.client.impl.WebTargetImpl.resolveTemplate(WebTargetImpl.java:25)
        at io.stargate.embedding.gateway.secrets.SyncServiceClient$SyncService$$QuarkusRestClientInterface.credential(Unknown Source)
        at io.stargate.embedding.gateway.secrets.SyncServiceClient$SyncService$$CDIWrapper.credential(Unknown Source)

```

**Comment by jeffreyscarpenter** [comment]
@Yuqi-Du Seems like there should also be a fix in the gateway to avoid NullPointerException
