### ISSUE TITLE
`SERVER_UNHANDLED_ERROR` from unmapped `io.grpc.StatusRuntimeException` (DEADLINE_EXCEEDED)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/data-api#1215]
One unmapped failure from Splunk logs:

```
stackTrace: : io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: ClientCall was cancelled at or after deadline. [remote_addr=/127.0.0.1:9002]
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at 
```

Not sure where exactly this comes from (calls to EmbeddingService?) but we should map this to some (new) `ErrorCode` (SERVER_GRPC_TIMEOUT ?)

**Comment by tatu-at-datastax** [comment]
I think this was wrt Bridge; but even if not, the whole exception handling has changed so this is probably not directly relevant -- should file new issues for unmapped exceptions still occurring.
