### ISSUE TITLE
timeuuid does not return a UNSUPPORTED+apiSupport block in listTables, rather a null

### ISSUE THREAD

**Issue by hemidactylus** [stargate/data-api#1568]
With this table

```
CREATE TABLE tablex (
    id timeuuid PRIMARY KEY,
    field2 tuple<text, text>
}
```

the listTables returns (notice the `"id": null`)

```
{
                "name": "tablex",
                "definition": {
                    "columns": {
                        "id": null,
                        "field2": {
                            "type": "UNSUPPORTED",
                            "apiSupport": {
                                "createTable": false,
                                "insert": false,
                                "read": false,
                                "cqlDefinition": "frozen<tuple<text, text>>"
                            }
                        }
                    },
                    "primaryKey": {
                        "partitionBy": [
                            "id"
                        ],
                        "partitionSort": {}
                    }
                }
            }
```

(slack [thread](https://datastax.slack.com/archives/C06P0MPSKLZ/p1729251302920279))

**Comment by hemidactylus** [comment]
Update: now, the presence of a TIMEUUID in a table leads to the whole "listTables(explain=true)" erorring with a 500 Int.Ser.Error:

```
{
    "errors": [
        {
            "message": "Server failed: root cause: (java.lang.IllegalArgumentException) No PrimitiveColumnDesc for apiDataType: PrimitiveApiDataTypeDef{typeName=TIMEUUID, cqlType=TIMEUUID}",
            "errorCode": "SERVER_UNHANDLED_ERROR",
            "id": "4a868910-509f-463d-b336-44329375cb2b",
            "title": "Server failed",
            "family": "SERVER",
            "scope": "DATABASE"
        }
    ]
}```

**Comment by amorton** [comment]
This was the error generated when there was a table with a timeuuid in it 

```
ERROR [vert.x-eventloop-thread-2] 2024-12-09 11:36:33,985 ThrowableToErrorMapper.java:280 - Unrecognized Exception (java.lang.IllegalArgumentException) caught, mapped to SERVER_UNHANDLED_ERROR: No PrimitiveColumnDesc for apiDataType: PrimitiveApiDataTypeDef{typeName=TIMEUUID, cqlType=TIMEUUID}: java.lang.IllegalArgumentException: No PrimitiveColumnDesc for apiDataType: PrimitiveApiDataTypeDef{typeName=TIMEUUID, cqlType=TIMEUUID}
	at io.stargate.sgv2.jsonapi.api.model.command.table.definition.datatype.PrimitiveColumnDesc.fromApiDataType(PrimitiveColumnDesc.java:76)
	at io.stargate.sgv2.jsonapi.service.schema.tables.PrimitiveApiDataTypeDef.columnDesc(PrimitiveApiDataTypeDef.java:57)
	at io.stargate.sgv2.jsonapi.service.schema.tables.ApiTableDef.lambda$toTableDesc$3(ApiTableDef.java:96)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at io.stargate.sgv2.jsonapi.service.schema.tables.ApiTableDef.toTableDesc(ApiTableDef.java:96)
	at io.stargate.sgv2.jsonapi.service.operation.ListTablesAttempt.lambda$getSchema$2(ListTablesAttempt.java:53)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

```

**Comment by amorton** [comment]
Progress update, ready other than tests.....

Given this CQL https://gist.github.com/amorton/7172ed435a49557907afcf7f4cc4b943

listTables output is https://gist.github.com/amorton/efebe5e928490ef0bf57b820ae83f13a

listIndexes output is https://gist.github.com/amorton/ddbc79869fd1c08b430388edb75c6bb9

can read and write things you should be able to, when reading from the nested collections table will get error

```json
{
    "errors": [
        {
            "message": "Only supported column types can be included when reading from a table.\n\nThe table unsupported.unsupported_nested_collections defines the columns: key(text), list_type(UNSUPPORTED CQL type: frozen<list<frozen<list<text>>>>), map_type(UNSUPPORTED CQL type: frozen<map<text, frozen<list<text>>>>), set_type(UNSUPPORTED CQL type: frozen<set<frozen<set<text>>>>).\nThe command included the following columns cannot be read: list_type(UNSUPPORTED CQL type: frozen<list<frozen<list<text>>>>), map_type(UNSUPPORTED CQL type: frozen<map<text, frozen<list<text>>>>), set_type(UNSUPPORTED CQL type: frozen<set<frozen<set<text>>>>).\n\nResend the command using only supported column types.",
            "scope": "PROJECTION",
            "errorCode": "UNSUPPORTED_COLUMN_TYPES",
            "id": "1952e8a0-0224-44af-a1d6-27edfeefcfe3",
            "family": "REQUEST",
            "title": "Column types in projection are not supported"
        }
    ]
}
```

When trying to write to insert a counter 

```json
{
    "errors": [
        {
            "message": "Only supported column types can be included when inserting a document into a table.\n\nThe table unsupported.unsupported_counter defines the columns: key(text), cnt(counter).\nThe command included the following columns that have unsupported data types: cnt(UNSUPPORTED CQL type: counter).\n\nResend the command using only supported column types.",
            "scope": "DOCUMENT",
            "errorCode": "UNSUPPORTED_COLUMN_TYPES",
            "id": "7f5a062d-064c-4bca-8997-8017fd60cad2",
            "family": "REQUEST",
            "title": "Column types in documents are not supported"
        }
    ]
}
```
