### ISSUE TITLE
HTTP 500 when sorting without constraining partition key 

### ISSUE THREAD

**Issue by toptobes** [stargate/data-api#1718]
Using primary key `{ partitionBy: [ 'text' ], partitionSort: { int: 1 } }`:

```
An unexpected server error occurred while processing the request. 

Error Class: InvalidQueryException

Error Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.
```

```
CommandFailedEvent {
  command: {
    find: {
      filter: {},
      projection: undefined,
      sort: { int: 1 },
      options: {
        includeSimilarity: undefined,
        includeSortVector: undefined,
        limit: undefined,
        skip: undefined,
        pageState: undefined
      }
    }
  },
  keyspace: 'other_keyspace',
  source: 'test_table',
  commandName: 'find',
  url: 'https://178588f6-149c-4de5-b93c-3178d6d18e53-us-west-2.apps.astra-dev.datastax.com/api/json/v1/other_keyspace/test_table',
  duration: 398.36283399999957,
  error: DataAPIHttpError: HTTP error (500): {"data":{"documents":[],"nextPageState":null},"status":{"warnings":[{"errorCode":"ZERO_FILTER_OPERATIONS","message":"Zero filters were provided in the filter for this query. \n\nProviding zero filters will return all rows in the table, which may have poor performance when the table is large. For the best performance, include one or more filters using the primary key or indexes.\n\nThe table other_keyspace.test_table has the primary key: text(text), int(int).\nAnd has indexes on the columns: vector.\n\nThe query was executed without taking advantage of the primary key or indexes on the table, this can have performance implications on large tables.\n\nSee documentation at XXXX for best practices for filtering.","family":"REQUEST","scope":"WARNING","title":"Zero operations provided in query filter","id":"4d601c08-3bba-4179-9ef6-70ca2e6413c7"}]},"errors":[{"message":"An unexpected server error occurred while processing the request. \n\nError Class: InvalidQueryException\nError Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.","scope":"","errorCode":"UNEXPECTED_SERVER_ERROR","id":"8210575e-7c8b-4548-b2aa-e904b7c800cb","family":"SERVER","title":"Unexpected server error"}]}
      at DataAPIHttpClient._requestDataAPI (/Users/kavin.gupta/Documents/work/astra-db-ts/src/lib/api/clients/data-api-http-client.ts:212:15)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at DataAPIHttpClient.executeCommand (/Users/kavin.gupta/Documents/work/astra-db-ts/src/lib/api/clients/data-api-http-client.ts:169:12)
      at TableFindCursor._FindCursor_getMore (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:621:17)
      at TableFindCursor._FindCursor_next (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:586:9)
      at TableFindCursor.[Symbol.asyncIterator] (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:496:21)
      at TableFindCursor.toArray (/Users/kavin.gupta/Documents/work/astra-db-ts/src/documents/cursor.ts:554:22)
      at Object.testFn (/Users/kavin.gupta/Documents/work/astra-db-ts/tests/integration/documents/tables/cursor.test.ts:210:19)
      at tryCatchErr (/Users/kavin.gupta/Documents/work/astra-db-ts/tests/testlib/utils.ts:26:5)
      at /Users/kavin.gupta/Documents/work/astra-db-ts/tests/testlib/test-fns/parallel.ts:107:20
      at async Promise.all (index 0)
      at async Promise.all (index 0)
      at Context.<anonymous> (/Users/kavin.gupta/Documents/work/astra-db-ts/tests/testlib/test-fns/parallel.ts:113:17) {
    status: 500,
    body: '...',
    raw: {
      headers: {
        server: 'openresty/1.25.3.1',
        date: 'Thu, 14 Nov 2024 07:25:02 GMT',
        'content-type': 'application/json;charset=UTF-8',
        'content-length': '1228'
      },
      body: '{"data":{"documents":[],"nextPageState":null},"status":{"warnings":[{"errorCode":"ZERO_FILTER_OPERATIONS","message":"Zero filters were provided in the filter for this query. \\n\\nProviding zero filters will return all rows in the table, which may have poor performance when the table is large. For the best performance, include one or more filters using the primary key or indexes.\\n\\nThe table other_keyspace.test_table has the primary key: text(text), int(int).\\nAnd has indexes on the columns: vector.\\n\\nThe query was executed without taking advantage of the primary key or indexes on the table, this can have performance implications on large tables.\\n\\nSee documentation at XXXX for best practices for filtering.","family":"REQUEST","scope":"WARNING","title":"Zero operations provided in query filter","id":"4d601c08-3bba-4179-9ef6-70ca2e6413c7"}]},"errors":[{"message":"An unexpected server error occurred while processing the request. \\n\\nError Class: InvalidQueryException\\nError Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.","scope":"","errorCode":"UNEXPECTED_SERVER_ERROR","id":"8210575e-7c8b-4548-b2aa-e904b7c800cb","family":"SERVER","title":"Unexpected server error"}]}',
      status: 500,
      url: 'https://178588f6-149c-4de5-b93c-3178d6d18e53-us-west-2.apps.astra-dev.datastax.com/api/json/v1/other_keyspace/test_table',
      httpVersion: 2,
      statusText: ''
    }
  }
}
```

**Comment by hemidactylus** [comment]
I see the same and added some CQL-flavored remarks here:

I got the impression that when the sorting is not "natural" with the clustering, the API  supposedly does its best to do in-memory (sacrificing pagination, issuing a warning and wasting resources; but still working). This is true for both find and findOne.

Now suppose I have a table with `((p_text), p_int)` (i.e. one partition key and one clustering column). The table also has a regular column `p_regular`.

* A user wants to `sort: {p_regular: 1}` and this works indeed.
* Another user wants to `sort: {p_int}` and this errors with a 500 and:

> An unexpected server error occurred while processing the request. \n\nError Class: InvalidQueryException\nError Message: ORDER BY is only supported when the partition key is restricted by an EQ or an IN.

_(conversely, if a filter on `p_text` is also specified, both work of course as the second case now fits the table partitioning neatly)_

It is my impression that in the second case (a clustering column in sorting, no partition specified), the query analyzer *mistakenly* goes the CQL route (instead of shrugging a bit and switching to in-memory-sort), which then attempts the following CQL and then leads to the error from C*:

```
SELECT p_boolean,p_text,p_int,p_int2,p_vector FROM default_keyspace.test_table_composite ORDER BY p_int ASC LIMIT 2147483647 ALLOW FILTERING
```

Q: Is it correct that both `find` forms above _should_ work?

**Comment by amorton** [comment]
fix looks like we need to run in memory sort when there is no filter. I did not realize this CQL restriction existed, even if we use allow filtering.

**Comment by amorton** [comment]
Merged to main and cherry picked into https://github.com/stargate/data-api/commits/feature/dec-hotfix/
