### ISSUE TITLE
CQL Session  blocks Eventloop thread

### ISSUE THREAD

**Issue by kathirsvn** [stargate/data-api#728]
The `getSession()` method in `CqlSessionCache` returns the session from the cache and if not present, tries to build it. Currently building the session is done in the event loop thread itself. So, if session creation takes more time, this might potentially block any new requests.

Below is an example from the logs, when a session gets created

```java
stargate-jsonapi-7c5895b967-fvkxt jsonapi WARN  [vertx-blocked-thread-checker] 2023-12-11 17:46:33,820 null:-1 - Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 3143 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at java.base@17.0.9/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:143)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at io.stargate.sgv2.jsonapi.service.cqldriver.CQLSessionCache.getNewSession(CQLSessionCache.java:119)
stargate-jsonapi-7c5895b967-fvkxt jsonapi 	at io.stargate.sgv2.jsonapi.service.cqldriver.CQLSessionCache$$Lambda$610/0x00007fd28452cdf0.load(Unknown Source)
```

**Comment by tatu-at-datastax** [comment]
@kathirsvn @maheshrajamani Is this still open or can we close the issue?

**Comment by amorton** [comment]
Closing. CQL session caching has been reworked
