### ISSUE TITLE
Java driver AllNodesFailedException on multiple operations

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/data-api#945]
From logs and metrics data, it seems that in a very small number of instances the API is returning AllNodesFailedException to the user instead of catching and mapping to a better exception message. For example, the following stack trace has been observed on CreateCollection and FindCollections at least, and possibly others:

```com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=null, hashCode=d7187f4): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node /127.0.0.1:9042: server replied with 'Provided username token and/or password are incorrect' to AuthResponse request]
    at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
    at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
    at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835)
    at io.stargate.sgv2.jsonapi.service.cqldriver.CQLSessionCache.getNewSession(CQLSessionCache.java:132)
    at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183)
    at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$2(LocalCache.java:167)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677)
    at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658)
    at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
    at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58)
    at io.stargate.sgv2.jsonapi.service.cqldriver.CQLSessionCache.getSession(CQLSessionCache.java:148)
    at io.stargate.sgv2.jsonapi.service.cqldriver.CQLSessionCache_ClientProxy.getSession(Unknown Source)
    at io.stargate.sgv2.jsonapi.service.operation.model.impl.FindCollectionsOperation.execute(FindCollectionsOperation.java:57)
    at io.stargate.sgv2.jsonapi.service.processor.CommandProcessor.lambda$processCommand$1(CommandProcessor.java:66)
    at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
    at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
    at ...
```

(Omitted portions of trace not related to the API)

**Comment by Hazel-Datastax** [comment]
The log isn't complete. The `AllNodesFailedException` on the top line is a parent exception class. We need a child exception to know the reason. While I checked the recent log, I found serval child errors:
```
com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=null, hashCode=1baded37): [com.datastax.oss.driver.api.core.auth.AuthenticationException: Authentication error on node /127.0.0.1:9042: server replied with 'Provided username token and/or password are incorrect' to AuthResponse request]
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
```

```
com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=null, hashCode=5d30840f): [java.lang.IllegalArgumentException: [s3256|control|id: 0xe01eedf2, L:/127.0.0.1:41174 - R:/127.0.0.1:9042] Protocol initialization request, step 3 (AUTH_RESPONSE): server replied with unexpected error code [SERVER_ERROR]: Internal error connecting to cluster]
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
```

```
com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at com.datastax.oss.driver.api.core.AllNodesFailedException.fromErrors(AllNodesFailedException.java:53)
```
The first error occurs most frequently
